name: gitleaks
on:
  pull_request:
    branches: [ master ]

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Environment file
        run: |
           docker pull zricethezav/gitleaks:v8.15.0
           docker run -v "$(pwd)":/path -v "gitleaks-results":/result zricethezav/gitleaks:v8.15.0 detect --source="/path" --report-path=/dev/stdout
